<?php

namespace App\Domain\Company;

enum AuditEventType: string
{
    case CompanyCreated = 'company_created';
    case CapabilityAssigned = 'capability_assigned';
    case CapabilityRevoked = 'capability_revoked';
    case SettingChanged = 'setting_changed';
    case SupplierCreated = 'supplier_created';
    case SupplierUpdated = 'supplier_updated';
    case SupplierArchived = 'supplier_archived';
    case SupplierRestored = 'supplier_restored';
    case SupplierContactCreated = 'supplier_contact_created';
    case SupplierContactUpdated = 'supplier_contact_updated';
    case CostCenterCreated = 'cost_center_created';
    case CostCenterRenamed = 'cost_center_renamed';
    case CostCenterArchived = 'cost_center_archived';
    case CostCenterRestored = 'cost_center_restored';
    case ExerciseCreated = 'exercise_created';
    case ExpenseCreated = 'expense_created';
    case ExpenseUpdated = 'expense_updated';
    case ExpenseMovedOrReclassified = 'expense_moved_or_reclassified';
    case ExpenseReversed = 'expense_reversed';
    case ExpenseRestored = 'expense_restored';
    case ExpenseLineCreated = 'expense_line_created';
    case ExpenseLineUpdated = 'expense_line_updated';
    case ExpenseLineAnnulled = 'expense_line_annulled';
    case ExpenseLineRestored = 'expense_line_restored';
    case ProjectCreated = 'project_created';
    case ProjectUpdated = 'project_updated';
    case ProjectTransitionPlanned = 'project_transition_planned';
    case ProjectTransitionEffective = 'project_transition_effective';
    case ProjectTransitionAnnulled = 'project_transition_annulled';
    case ProjectTransitionReplaced = 'project_transition_replaced';
    case ProjectClassificationChanged = 'project_classification_changed';
    case ProjectOverspendCreated = 'project_overspend_created';
    case ProjectOverspendIncreased = 'project_overspend_increased';
    case ProjectArchived = 'project_archived';
    case ProjectRestored = 'project_restored';
    case ProjectDeferralChanged = 'project_deferral_changed';
    case ContractCreated = 'contract_created';
    case ContractCensused = 'contract_censused';
    case ContractUpdated = 'contract_updated';
    case ContractActivation = 'contract_activation';
    case ContractRenewed = 'contract_renewed';
    case ContractRenewalChanged = 'contract_renewal_changed';
    case ContractCessated = 'contract_cessated';
    case ContractReactivated = 'contract_reactivated';
    case ContractCancelled = 'contract_cancelled';
    case ContractLifecycleFactAnnulled = 'contract_lifecycle_fact_annulled';
    case ContractLifecycleFactReplaced = 'contract_lifecycle_fact_replaced';
    case ContractConditionCreated = 'contract_condition_created';
    case ContractConditionChanged = 'contract_condition_changed';
    case ContractConditionCorrected = 'contract_condition_corrected';
    case ContractConditionAnnulled = 'contract_condition_annulled';
    case ContractConditionRestored = 'contract_condition_restored';
    case ContractEstimateRecalculated = 'contract_estimate_recalculated';
    case ContractClassificationChanged = 'contract_classification_changed';
    case ProjectContractLinked = 'project_contract_linked';
    case ProjectContractLinkArchived = 'project_contract_link_archived';
    case ProjectContractLinkRestored = 'project_contract_link_restored';
    case ContractArchived = 'contract_archived';
    case ContractRestored = 'contract_restored';
    case AttachmentUploaded = 'attachment_uploaded';
    case AttachmentDetached = 'attachment_detached';
    case ProposalInitialized = 'proposal_initialized';
    case ProposalRevisionInitialized = 'proposal_revision_initialized';
    case ProposalSourceIncluded = 'proposal_source_included';
    case ProposalSourceAcknowledged = 'proposal_source_acknowledged';
    case ProposalActionPlanned = 'proposal_action_planned';
    case ProposalActionWithdrawn = 'proposal_action_withdrawn';
    case ProposalActionApplied = 'proposal_action_applied';
    case ProposalReadinessReviewed = 'proposal_readiness_reviewed';
    case ProposalMarkedToRealign = 'proposal_marked_to_realign';
    case ProposalRealityReloaded = 'proposal_reality_reloaded';
    case ProposalPlanKept = 'proposal_plan_kept';
    case ProposalManuallyRealigned = 'proposal_manually_realigned';
    case ProposalApproved = 'proposal_approved';
    case ProposalDiscarded = 'proposal_discarded';
    case ProposalApprovalFailed = 'proposal_approval_failed';
    case BudgetCreated = 'budget_created';
    case BudgetRevisionCreated = 'budget_revision_created';
    case HistoricalDivergenceRecorded = 'historical_divergence_recorded';

    public function label(): string
    {
        return match ($this) {
            self::CompanyCreated => 'Azienda creata',
            self::CapabilityAssigned => 'Capacità assegnata',
            self::CapabilityRevoked => 'Capacità revocata',
            self::SettingChanged => 'Impostazione modificata',
            self::SupplierCreated => 'Fornitore creato',
            self::SupplierUpdated => 'Fornitore modificato',
            self::SupplierArchived => 'Fornitore archiviato',
            self::SupplierRestored => 'Fornitore ripristinato',
            self::SupplierContactCreated => 'Referente creato',
            self::SupplierContactUpdated => 'Referente modificato',
            self::CostCenterCreated => 'Centro di Costo creato',
            self::CostCenterRenamed => 'Centro di Costo rinominato',
            self::CostCenterArchived => 'Centro di Costo archiviato',
            self::CostCenterRestored => 'Centro di Costo ripristinato',
            self::ExerciseCreated => 'Esercizio creato',
            self::ExpenseCreated => 'Spesa creata',
            self::ExpenseUpdated => 'Spesa modificata',
            self::ExpenseMovedOrReclassified => 'Spesa spostata o riclassificata',
            self::ExpenseReversed => 'Spesa stornata',
            self::ExpenseRestored => 'Spesa ripristinata',
            self::ExpenseLineCreated => 'Riga creata',
            self::ExpenseLineUpdated => 'Riga modificata',
            self::ExpenseLineAnnulled => 'Riga annullata',
            self::ExpenseLineRestored => 'Riga ripristinata',
            self::ProjectCreated => 'Progetto creato',
            self::ProjectUpdated => 'Progetto modificato',
            self::ProjectTransitionPlanned => 'Transizione progetto pianificata',
            self::ProjectTransitionEffective => 'Transizione progetto efficace',
            self::ProjectTransitionAnnulled => 'Transizione progetto annullata',
            self::ProjectTransitionReplaced => 'Transizione progetto sostituita',
            self::ProjectClassificationChanged => 'Classificazione progetto modificata',
            self::ProjectOverspendCreated => 'Sovraspesa progetto creata',
            self::ProjectOverspendIncreased => 'Sovraspesa progetto aumentata',
            self::ProjectArchived => 'Progetto archiviato',
            self::ProjectRestored => 'Progetto ripristinato',
            self::ProjectDeferralChanged => 'Rinvio progetto modificato',
            self::ContractCreated => 'Contratto creato',
            self::ContractCensused => 'Contratto censito tardivamente',
            self::ContractUpdated => 'Contratto modificato',
            self::ContractActivation => 'Contratto attivato',
            self::ContractRenewed => 'Contratto rinnovato',
            self::ContractRenewalChanged => 'Configurazione rinnovo modificata',
            self::ContractCessated => 'Contratto cessato',
            self::ContractReactivated => 'Contratto riattivato',
            self::ContractCancelled => 'Contratto annullato',
            self::ContractLifecycleFactAnnulled => 'Evento contrattuale annullato',
            self::ContractLifecycleFactReplaced => 'Evento contrattuale sostituito',
            self::ContractConditionCreated => 'Condizione contrattuale creata',
            self::ContractConditionChanged => 'Condizione contrattuale modificata',
            self::ContractConditionCorrected => 'Condizione contrattuale corretta',
            self::ContractConditionAnnulled => 'Condizione contrattuale annullata',
            self::ContractConditionRestored => 'Condizione contrattuale ripristinata',
            self::ContractEstimateRecalculated => 'Stima contrattuale ricalcolata',
            self::ContractClassificationChanged => 'Classificazione contratto modificata',
            self::ProjectContractLinked => 'Progetto e Contratto collegati',
            self::ProjectContractLinkArchived => 'Collegamento Progetto-Contratto archiviato',
            self::ProjectContractLinkRestored => 'Collegamento Progetto-Contratto ripristinato',
            self::ContractArchived => 'Contratto archiviato',
            self::ContractRestored => 'Contratto ripristinato',
            self::AttachmentUploaded => 'Allegato caricato',
            self::AttachmentDetached => 'Allegato rimosso dall’oggetto',
            self::ProposalInitialized => 'Proposta inizializzata',
            self::ProposalRevisionInitialized => 'Revisione inizializzata',
            self::ProposalSourceIncluded => 'Sorgente inclusa nella proposta',
            self::ProposalSourceAcknowledged => 'Sorgente presa in visione',
            self::ProposalActionPlanned => 'Decisione di piano registrata',
            self::ProposalActionWithdrawn => 'Decisione di piano ritirata',
            self::ProposalActionApplied => 'Decisione di piano applicata',
            self::ProposalReadinessReviewed => 'Verifiche proposta ricalcolate',
            self::ProposalMarkedToRealign => 'Sorgente proposta da riallineare',
            self::ProposalRealityReloaded => 'Realtà ricaricata nella proposta',
            self::ProposalPlanKept => 'Decisioni di proposta mantenute',
            self::ProposalManuallyRealigned => 'Sorgente riallineata manualmente',
            self::ProposalApproved => 'Proposta approvata',
            self::ProposalDiscarded => 'Proposta scartata',
            self::ProposalApprovalFailed => 'Approvazione proposta fallita',
            self::BudgetCreated => 'Budget creato',
            self::BudgetRevisionCreated => 'Revisione Budget creata',
            self::HistoricalDivergenceRecorded => 'Divergenza storica registrata',
        };
    }
}
