<?php

namespace App\Domain\Company;

enum AuditEventType: string
{
    case CompanyCreated = 'company_created';
    case SettingChanged = 'setting_changed';
    case SupplierCreated = 'supplier_created';
    case SupplierUpdated = 'supplier_updated';
    case SupplierArchived = 'supplier_archived';
    case SupplierRestored = 'supplier_restored';
    case SupplierContactCreated = 'supplier_contact_created';
    case SupplierContactUpdated = 'supplier_contact_updated';
    case CostCenterCreated = 'cost_center_created';
    case CostCenterRenamed = 'cost_center_renamed';
    case CostCenterArchived = 'cost_center_archived';
    case CostCenterRestored = 'cost_center_restored';
    case ExerciseCreated = 'exercise_created';
    case ExerciseClosingStarted = 'exercise_closing_started';
    case ExerciseClosingConfirmed = 'exercise_closing_confirmed';
    case ExerciseClosed = 'exercise_closed';
    case ExerciseClosingFailed = 'exercise_closing_failed';
    case NextExerciseNotCreated = 'next_exercise_not_created';
    case ExpenseCreated = 'expense_created';
    case ExpenseUpdated = 'expense_updated';
    case ExpenseMovedOrReclassified = 'expense_moved_or_reclassified';
    case ExpenseReversed = 'expense_reversed';
    case ExpenseRestored = 'expense_restored';
    case ExpenseLineCreated = 'expense_line_created';
    case ExpenseLineUpdated = 'expense_line_updated';
    case ExpenseLineAnnulled = 'expense_line_annulled';
    case ExpenseLineRestored = 'expense_line_restored';
    case ProjectCreated = 'project_created';
    case ProjectUpdated = 'project_updated';
    case ProjectTransitionPlanned = 'project_transition_planned';
    case ProjectTransitionEffective = 'project_transition_effective';
    case ProjectTransitionAnnulled = 'project_transition_annulled';
    case ProjectTransitionReplaced = 'project_transition_replaced';
    case ProjectClassificationChanged = 'project_classification_changed';
    case ProjectOverspendCreated = 'project_overspend_created';
    case ProjectOverspendIncreased = 'project_overspend_increased';
    case ProjectArchived = 'project_archived';
    case ProjectRestored = 'project_restored';
    case ProjectDeferralChanged = 'project_deferral_changed';
    case ProjectCarryoverConsolidated = 'project_carryover_consolidated';
    case ProjectClosedWithSaving = 'project_closed_with_saving';
    case ProjectCancelledWithUnusedAllocation = 'project_cancelled_with_unused_allocation';
    case ContractCreated = 'contract_created';
    case ContractCensused = 'contract_censused';
    case ContractUpdated = 'contract_updated';
    case ContractActivation = 'contract_activation';
    case ContractRenewed = 'contract_renewed';
    case ContractRenewalChanged = 'contract_renewal_changed';
    case ContractCessated = 'contract_cessated';
    case ContractReactivated = 'contract_reactivated';
    case ContractCancelled = 'contract_cancelled';
    case ContractLifecycleFactAnnulled = 'contract_lifecycle_fact_annulled';
    case ContractLifecycleFactReplaced = 'contract_lifecycle_fact_replaced';
    case ContractConditionCreated = 'contract_condition_created';
    case ContractConditionChanged = 'contract_condition_changed';
    case ContractConditionCorrected = 'contract_condition_corrected';
    case ContractConditionAnnulled = 'contract_condition_annulled';
    case ContractConditionRestored = 'contract_condition_restored';
    case ContractEstimateRecalculated = 'contract_estimate_recalculated';
    case ContractClassificationChanged = 'contract_classification_changed';
    case ProjectContractLinked = 'project_contract_linked';
    case ProjectContractLinkArchived = 'project_contract_link_archived';
    case ProjectContractLinkRestored = 'project_contract_link_restored';
    case ContractArchived = 'contract_archived';
    case ContractRestored = 'contract_restored';
    case AttachmentUploaded = 'attachment_uploaded';
    case AttachmentDetached = 'attachment_detached';
    case ProposalInitialized = 'proposal_initialized';
    case ProposalRevisionInitialized = 'proposal_revision_initialized';
    case ProposalSourceIncluded = 'proposal_source_included';
    case ProposalSourceAcknowledged = 'proposal_source_acknowledged';
    case ProposalActionPlanned = 'proposal_action_planned';
    case ProposalActionWithdrawn = 'proposal_action_withdrawn';
    case ProposalActionApplied = 'proposal_action_applied';
    case ProposalReadinessReviewed = 'proposal_readiness_reviewed';
    case ProposalMarkedToRealign = 'proposal_marked_to_realign';
    case ProposalRealityReloaded = 'proposal_reality_reloaded';
    case ProposalPlanKept = 'proposal_plan_kept';
    case ProposalManuallyRealigned = 'proposal_manually_realigned';
    case ProposalApproved = 'proposal_approved';
    case ProposalDiscarded = 'proposal_discarded';
    case ProposalApprovalFailed = 'proposal_approval_failed';
    case BudgetCreated = 'budget_created';
    case BudgetRevisionCreated = 'budget_revision_created';
    case HistoricalDivergenceRecorded = 'historical_divergence_recorded';
    case LateCorrectionRecorded = 'late_correction_recorded';
    case HistoricalErrorAnnotationRecorded = 'historical_error_annotation_recorded';

    public function label(): string
    {
        return match ($this) {
            self::CompanyCreated => 'Azienda Creata',
            self::SettingChanged => 'Impostazione Modificata',
            self::SupplierCreated => 'Fornitore Creato',
            self::SupplierUpdated => 'Fornitore Modificato',
            self::SupplierArchived => 'Fornitore Archiviato',
            self::SupplierRestored => 'Fornitore Ripristinato',
            self::SupplierContactCreated => 'Referente Creato',
            self::SupplierContactUpdated => 'Referente Modificato',
            self::CostCenterCreated => 'Centro di Costo Creato',
            self::CostCenterRenamed => 'Centro di Costo Rinominato',
            self::CostCenterArchived => 'Centro di Costo Archiviato',
            self::CostCenterRestored => 'Centro di Costo Ripristinato',
            self::ExerciseCreated => 'Esercizio Creato',
            self::ExerciseClosingStarted => 'Chiusura Esercizio Avviata',
            self::ExerciseClosingConfirmed => 'Chiusura Esercizio Confermata',
            self::ExerciseClosed => 'Esercizio Chiuso',
            self::ExerciseClosingFailed => 'Chiusura Esercizio Fallita',
            self::NextExerciseNotCreated => 'Esercizio Successivo Non Creato',
            self::ExpenseCreated => 'Spesa Creata',
            self::ExpenseUpdated => 'Spesa Modificata',
            self::ExpenseMovedOrReclassified => 'Spesa Spostata o Riclassificata',
            self::ExpenseReversed => 'Spesa Stornata',
            self::ExpenseRestored => 'Spesa Ripristinata',
            self::ExpenseLineCreated => 'Riga Creata',
            self::ExpenseLineUpdated => 'Riga Modificata',
            self::ExpenseLineAnnulled => 'Riga Annullata',
            self::ExpenseLineRestored => 'Riga Ripristinata',
            self::ProjectCreated => 'Progetto Creato',
            self::ProjectUpdated => 'Progetto Modificato',
            self::ProjectTransitionPlanned => 'Transizione Progetto Pianificata',
            self::ProjectTransitionEffective => 'Transizione Progetto Efficace',
            self::ProjectTransitionAnnulled => 'Transizione Progetto Annullata',
            self::ProjectTransitionReplaced => 'Transizione Progetto Sostituita',
            self::ProjectClassificationChanged => 'Classificazione Progetto Modificata',
            self::ProjectOverspendCreated => 'Sovraspesa Progetto Creata',
            self::ProjectOverspendIncreased => 'Sovraspesa Progetto Aumentata',
            self::ProjectArchived => 'Progetto Archiviato',
            self::ProjectRestored => 'Progetto Ripristinato',
            self::ProjectDeferralChanged => 'Rinvio Progetto Modificato',
            self::ProjectCarryoverConsolidated => 'Riporto Progetto Consolidato',
            self::ProjectClosedWithSaving => 'Progetto Chiuso con Risparmio',
            self::ProjectCancelledWithUnusedAllocation => 'Progetto Cancellato con Allocato Non Utilizzato',
            self::ContractCreated => 'Contratto Creato',
            self::ContractCensused => 'Contratto Censito Tardivamente',
            self::ContractUpdated => 'Contratto Modificato',
            self::ContractActivation => 'Contratto Attivato',
            self::ContractRenewed => 'Contratto Rinnovato',
            self::ContractRenewalChanged => 'Configurazione Rinnovo Modificata',
            self::ContractCessated => 'Contratto Cessato',
            self::ContractReactivated => 'Contratto Riattivato',
            self::ContractCancelled => 'Contratto Annullato',
            self::ContractLifecycleFactAnnulled => 'Evento Contrattuale Annullato',
            self::ContractLifecycleFactReplaced => 'Evento Contrattuale Sostituito',
            self::ContractConditionCreated => 'Condizione Contrattuale Creata',
            self::ContractConditionChanged => 'Condizione Contrattuale Modificata',
            self::ContractConditionCorrected => 'Condizione Contrattuale Corretta',
            self::ContractConditionAnnulled => 'Condizione Contrattuale Annullata',
            self::ContractConditionRestored => 'Condizione Contrattuale Ripristinata',
            self::ContractEstimateRecalculated => 'Stima Contrattuale Ricalcolata',
            self::ContractClassificationChanged => 'Classificazione Contratto Modificata',
            self::ProjectContractLinked => 'Progetto e Contratto Collegati',
            self::ProjectContractLinkArchived => 'Collegamento Progetto-Contratto Archiviato',
            self::ProjectContractLinkRestored => 'Collegamento Progetto-Contratto Ripristinato',
            self::ContractArchived => 'Contratto Archiviato',
            self::ContractRestored => 'Contratto Ripristinato',
            self::AttachmentUploaded => 'Allegato Caricato',
            self::AttachmentDetached => 'Allegato Rimosso dall’Oggetto',
            self::ProposalInitialized => 'Proposta Inizializzata',
            self::ProposalRevisionInitialized => 'Revisione Inizializzata',
            self::ProposalSourceIncluded => 'Sorgente Inclusa nella Proposta',
            self::ProposalSourceAcknowledged => 'Sorgente Presa in Visione',
            self::ProposalActionPlanned => 'Decisione di Piano Registrata',
            self::ProposalActionWithdrawn => 'Decisione di Piano Ritirata',
            self::ProposalActionApplied => 'Decisione di Piano Applicata',
            self::ProposalReadinessReviewed => 'Verifiche Proposta Ricalcolate',
            self::ProposalMarkedToRealign => 'Sorgente Proposta da Riallineare',
            self::ProposalRealityReloaded => 'Realtà Ricaricata nella Proposta',
            self::ProposalPlanKept => 'Decisioni di Proposta Mantenute',
            self::ProposalManuallyRealigned => 'Sorgente Riallineata Manualmente',
            self::ProposalApproved => 'Proposta Approvata',
            self::ProposalDiscarded => 'Proposta Scartata',
            self::ProposalApprovalFailed => 'Approvazione Proposta Fallita',
            self::BudgetCreated => 'Budget Creato',
            self::BudgetRevisionCreated => 'Revisione Budget Creata',
            self::HistoricalDivergenceRecorded => 'Divergenza Storica Registrata',
            self::LateCorrectionRecorded => 'Correzione Tardiva Registrata',
            self::HistoricalErrorAnnotationRecorded => 'Annotazione di Errore Storico Registrata',
        };
    }
}
